### ISSUE TITLE
hoge

### ISSUE THREAD

**Issue by kodandy** [besutome/battwitter#1]
[![LGTM! Please wait until the image is uploaded...](https://dl.dropboxusercontent.com/1/view/f4ec40s5x5i6zxq/lgtm/1443967238.593683.gif)](http://takashicompany.com/lgtm)

**Comment by besutome** [comment]
[![LGTM! Please wait until the image is uploaded...](https://dl.dropboxusercontent.com/1/view/3cptdhkdwx36f6s/lgtm/1443967548.236814.gif)](http://takashicompany.com/lgtm)

**Comment by besutome** [comment]
[![LGTM! Please wait until the image is uploaded...](https://dl.dropboxusercontent.com/1/view/3cptdhkdwx36f6s/lgtm/1443967548.236814.gif)](http://takashicompany.com/lgtm)

**Comment by kodandy** [comment]
[![LGTM! Please wait until the image is uploaded...](https://dl.dropboxusercontent.com/1/view/3cptdhkdwx36f6s/lgtm/1443967548.236814.gif)](http://takashicompany.com/lgtm)
