### ISSUE TITLE
ds

### ISSUE THREAD

**Issue by kodandy** [besutome/battwitter#3]
hoge

**Comment by kodandy** [comment]
[![LGTM! Please wait until the image is uploaded...](https://dl.dropboxusercontent.com/1/view/3cptdhkdwx36f6s/lgtm/1443967548.236814.gif)](http://takashicompany.com/lgtm)

**Comment by kodandy** [comment]
[![LGTM! Please wait until the image is uploaded...](https://dl.dropboxusercontent.com/1/view/3cptdhkdwx36f6s/lgtm/1443967548.236814.gif)](http://takashicompany.com/lgtm)

**Comment by kodandy** [comment]
[![LGTM! Please wait until the image is uploaded...](https://dl.dropboxusercontent.com/1/view/3cptdhkdwx36f6s/lgtm/1443967548.236814.gif)](http://takashicompany.com/lgtm)

**Comment by kodandy** [comment]
[![LGTM! Please wait until the image is uploaded...](https://dl.dropboxusercontent.com/1/view/3cptdhkdwx36f6s/lgtm/1443967548.236814.gif)](http://takashicompany.com/lgtm)

**Comment by kodandy** [comment]
[![LGTM! Please wait until the image is uploaded...](http://takashicompany.com/lgtm_random/random.gif?r=' + Math.floor%28Math.random%28%29 * 1000000000%29 + '_' + new Date%28).getTime() + ")](http://takashicompany.com/lgtm)

**Comment by kodandy** [comment]
[![LGTM! Please wait until the image is uploaded...](http://takashicompany.com/lgtm)

**Comment by kodandy** [comment]
[![LGTM! Please wait until the image is uploaded...]

**Comment by kodandy** [comment]
[![LGTM! Please wait until the image is uploaded...](http://takashicompany.com/lgtm_random/random.gif?r=' + Math.floor%28Math.random%28%29 * 1000000000%29 + '_' + new Date%28)](http://takashicompany.com/lgtm)

**Comment by kodandy** [comment]
[![LGTM! Please wait until the image is uploaded...](http://takashicompany.com/lgtm_random/random.gif?r=' + Math.floor%28Math.random%28%29 * 1000000000%29 + '_' + new Date%28).getTime() + ")](http://takashicompany.com/lgtm)")();

**Comment by kodandy** [comment]
[![LGTM! Please wait until the image is uploaded...](https://dl.dropboxusercontent.com/1/view/3cptdhkdwx36f6s/lgtm/1443967548.236814.gif)](http://takashicompany.com/lgtm)

**Comment by besutome** [comment]
http://takashicompany.com/lgtm_random/random.gif?r=' + Math.floor(Math.random() * 1000000000

**Comment by kodandy** [comment]
[![LGTM! Please wait until the image is uploaded...](http://takashicompany.com/lgtm_random/random.gif?r=' + Math.floor%28Math.random%28%29 * 1000000000%29 + '_' + new Date%28).getTime() + ")](http://takashicompany.com/lgtm)
